services:
  flask-app:
    build:
      context: flask-app
      dockerfile: Dockerfile
    image: grexdin/flask-app:${IMAGE_TAG:-latest}
  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: grexdin/flask-app-nginx:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - flask-app
